from .CosineSimilarityLoss import *
from .SoftmaxLoss import *
from .MultipleNegativesRankingLoss import *
from .MultipleNegativesSymmetricRankingLoss import *
from .TripletLoss import *
from .MarginMSELoss import MarginMSELoss
from .MSELoss import *
from .ContrastiveLoss import *
from .ContrastiveTensionLoss import *
from .OnlineContrastiveLoss import *
from .MegaBatchMarginLoss import *
from .DenoisingAutoEncoderLoss import *

from .BatchHardTripletLoss import *
from .BatchHardSoftMarginTripletLoss import *
from .BatchSemiHardTripletLoss import *
from .BatchAllTripletLoss import *
from .BYOLoss import *
from .BarlowLoss import *
from .VICRegLoss import *
from .CorInfoMaxLoss import *